const DataPantalla = [
    {
        pantalla: "Instrumentos Acciones",
        id: 1,
        observacion: "",
        idRestriccion: 0,
    },
    {
        pantalla: "Proceso Renta Variable",
        id: 1,
        observacion: "",
        idRestriccion: 24,
    },
    {
        pantalla: "Proceso Eurobonos",
        id: 1,
        observacion: "",
        idRestriccion: 6,
    },
    {
        pantalla: "Calificaciones Emisoras",
        id: 2,
        observacion: "",
        idRestriccion: 2,
    },
    {
        pantalla: "Calificaciones Fondos",
        id: 2,
        observacion: "",
        idRestriccion: 2,
    },
    {
        pantalla: "Calificaciones Instrumentos",
        id: 2,
        observacion: "",
        idRestriccion: 2,
    },
    {
        pantalla: "Calificaciones Programas",
        id: 2,
        observacion: "",
        idRestriccion: 2,
    },
    {
        pantalla: "Catalgos Mexico",
        id: 3,
        observacion: "",
        idRestriccion: 3,
    },
    {
        pantalla: "Catalogos Archivos",
        id: 3,
        observacion: "",
        idRestriccion: 3,
    },
    {
        pantalla: "Catalogos Class Sectorial",
        id: 3,
        observacion: "",
        idRestriccion: 3
    },
    {
        pantalla: "Instrumentos Corp-Banc",
        id: 4,
        observacion: "",
        idRestriccion: 5,
    },
    {
        pantalla: "Clasificacion Sectorial",
        id: 5,
        observacion: "",
        idRestriccion: 5,
    },
    {
        pantalla: "Instrumentos Gubernamentales",
        id: 5,
        observacion: "",
        idResticcion: 5,
    },
    {
        pantalla: "Valida Nodos Curvas",
        id: 5,
        observacion: "",
        idRestriccion: 5,
    },
    {
        pantalla: "Instrumentos Internacionales",
        id: 6,
        observacion: "",
        idRestriccion: 6,
    },
    {
        pantalla: "Panama",
        id: 8,
        observacion: "",
        idRestriccion: 8,
    },
    {
        pantalla: "Usuarios",
        id: 9,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Matrices Transpuestas por Instrumento",
        id: 9,
        observacion: "comentado",
        idRestriccion: 9,
    },
    {
        pantalla: "CAU Consta Rica",
        id: 10,
        observacion: "",
        idRestriccion: 10,
    },
    {
        pantalla: "Mantenimiento CAU",
        id: 10,
        observacion: "",
        idRestriccion: 10,
    },
    {
        pantalla: "Mantenimiento CAU Modificación",
        id: 13,
        observacion: "",
        idRestriccion: 13,
    },
    {
        pantalla: "Catalogos Panama",
        id: 11,
        observacion: "",
        idRestriccion: 11,
    },
    {
        pantalla: "Catalogos CAU",
        id: 12,
        observacion: "",
        idRestriccion: 12,
    },
    {
        pantalla: "Catalogos Costa Rica",
        id: 14,
        observacion: "",
        idRestriccion: 14,
    },
    {
        pantalla: "Catalogos Perfil",
        id: 14,
        observacion: "",
        idRestriccion: 14,
    },
    {
        pantalla: "Consulta CR",
        id: 14,
        observacion: "comentado",
        idRestriccion: 14,
    },
    {
        pantalla: "Costa Rica",
        id: 14,
        observacion: "",
        idRestriccion: 14,
    },
    {
        pantalla: "Subastas CR",
        id: 14,
        observacion: "",
        idRestriccion: 14,
    },
    {
        pantalla: "Catalogos Base Accionaria",
        id: 15,
        observacion: "",
        idRestriccion: 24,
    },
    {
        pantalla: "Catalogos Brokers",
        id: 15,
        observacion: "",
        idRestriccion: 24,
    },
    {
        pantalla: "Catalogos Calificaciones",
        id: 15,
        observacion: "",
        idRestriccion: 15,
    },
    {
        pantalla: "Envios Mail Valmer",
        id: 17,
        observacion: "",
        idRestriccion: 17,
    },
    {
        pantalla: "Historico Calificaciones Emisoras",
        id: 18,
        observacion: "",
        idRestriccion: 18,
    },
    {
        pantalla: "Historico Calificaciones Instrumentos",
        id: 18,
        observacion: "",
        idRestriccion: 18,
    },
    {
        pantalla: "Historico",
        id: 19,
        observacion: "",
        idRestriccion: 5,
    },
    {
        pantalla: "Instrumentos Derivados - Listados",
        id: 20,
        observacion: "",
        idRestriccion: 20,
    },
    {
        pantalla: "Instrumentos Derivados - Chicago",
        id: 20,
        observacion: "",
        idRestriccion: 20,
    },
    {
        pantalla: "Instrumentos Derivados - Teoricos",
        id: 20,
        observacion: "",
        idRestriccion: 20,
    },
    {
        pantalla: "Consulta Brokers Total Hechos y Posturas",
        id: 24,
        observacion: "",
        idRestriccion: 24,
    },
    {
        pantalla: "Curvas Especiales",
        id: 24,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Brokers Electronicos Gubernamentales",
        id: 27,
        observacion: "",
        idRestriccion: 27,
    },
    {
        pantalla: "Brokers Electronicos Corporativos",
        id: 27,
        observacion: "",
        idRestriccion: 27,
    },
    {
        pantalla: "Curvas Derivados",
        id: 27,
        observacion: "",
        idRestriccion: 27,
    },
    {
        pantalla: "Curvas Derivados",
        id: 27,
        observacion: "",
        idRestriccion: 27,
    },
    {
        pantalla: "Lipper Fund",
        id: 30,
        observacion: "comentado",
        idRestriccion: 0,
    },
    {
        pantalla: "CI Norm Auditoria Ext",
        id: 30,
        observacion: "",
        idRestriccion: 30,
    },
    {
        pantalla: "CI Norm Auditoria Int",
        id: 30,
        observacion: "",
        idRestriccion: 30,
    },
    {
        pantalla: "CI Norm Obligaciones",
        id: 30,
        observacion: "",
        idRestriccion: 30,
    },
    {
        pantalla: "Clientes Formatos Derivados",
        id: 30,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Derivados Chicago Alta",
        id: 30,
        observacion: "",
        idRestriccion: 30,
    },
    {
        pantalla: "Derivados OTC",
        id: 30,
        observacion: "",
        idRestriccion: 30,
    },
    {
        pantalla: "Layouts Derivados",
        id: 30,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Operaciones Derivados",
        id: 30,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Proceso Derivados",
        id: 30,
        observacion: "",
        idRestriccion: 30,
    },
    {
        pantalla: "Swp Asigna Consecutivos",
        id: 30,
        observacion: "",
        idRestriccion: 30,
    },
    {
        pantalla: "Configuración Usuarios Web Valmer",
        id: 31,
        observacion: "",
        idRestriccion: 31,
    },
    {
        pantalla: "Configuracion Usuarios Web Valmer Permisos",
        id: 31,
        observacion: "",
        idRestriccion: 31,
    },
    {
        pantalla: "Vector PIP MD",
        id: 32,
        observacion: "",
        idRestriccion: 0,
    },
    {
        pantalla: "Carga Track ESGMEX",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Derivados Valrisk",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Riesgos Factores Riesgo",
        id: 32,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Riesgos Proceso Fonacot",
        id: 32,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Usuarios Valrisk",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Carga Matrices Valrisk",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Carga Trayectorias Valrisk",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Consulta de Calculos",
        id: 32,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Consulta de Carteras",
        id: 32,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Consulta Instrumento",
        id: 32,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Consulta de Insumos",
        id: 32,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Consulta Riesgo Credito Valrisk",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Valrisk Error Seguimiento",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Probabilidad Incumplimiento Valrisk",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Proceso Fira",
        id: 32,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Vector HSBC",
        id: 32,
        observacion: "",
        idRestriccion: 9,
    },
    {
        pantalla: "Matriz de Sobretasas Valrisk",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Genera Reporte Liquidez Cartera Cliente",
        id: 32,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Tasas Intranet",
        id: 33,
        observacion: "",
        idRestriccion: 33,
    },
    {
        pantalla: "Subastas",
        id: 33,
        observacion: "",
        idRestriccion: 33,
    },
    {
        pantalla: "Subastas Flotantes",
        id: 33,
        observacion: "",
        idRestriccion: 33,
    },
    {
        pantalla: "Tasas",
        id: 33,
        observacion: "",
        idRestriccion: 33,
    },
    {
        pantalla: "Reuters Liquidez Latam",
        id: 34,
        observacion: "",
        idRestriccion: 34,
    },
    {
        pantalla: "Reuters UMS Mex",
        id: 34,
        observacion: "",
        idRestriccion: 34,
    },
    {
        pantalla: "Reuters UMS Latam",
        id: 34,
        observacion: "",
        idRestriccion: 34,
    },
    {
        pantalla: "Notas Complejas",
        id: 35,
        observacion: "",
        idRestriccion: 32,
    },
    {
        pantalla: "Proceso Notas Estructuradas",
        id: 35,
        observacion: "",
        idRestriccion: 35,
    },
    {
        pantalla: "Proceso Notas Estructuradas Exoticas",
        id: 35,
        observacion: "",
        idRestriccion: 35,
    },
    {
        pantalla: "Subyacentes",
        id: 35,
        observacion: "",
        idRestriccion: 35,
    },
    {
        pantalla: "Mensajeria Valmer",
        id: 36,
        observacion: "",
        idRestriccion: 36,
    },
    {
        pantalla: "Definición Instrumentos Derivados",
        id: 0,
        observacion: "",
        idRestriccion: 0,
    },
    {
        pantalla: "Definicion Instrumentos Derivados",
        id: 0,
        observacion: "",
        idRestriccion: 0,
    },
    {
        pantalla: "Index",
        id: 0,
        observacion: "",
        idRestriccion: 0,
    },
    {
        pantalla: "Index In",
        id: 0,
        observacion: "",
        idRestriccion: 0,
    },
    {
        pantalla: "Regimen de Inversion",
        id: 17,
        observacion: "",
        idRestriccion: 17,
    }
]

export function getIdView(view: string): number {
    return DataPantalla.find(v => v.pantalla === view)!.id;
}