export interface FormValuesInter {
    [key: string]: string | FlujosInter[];
}

export interface FlujosInter {
    property: string;
    data: FlujosDataHist | FlujosDataVal
}

export interface FlujosDataHist {
    d_fecha_ini_cupon: string;
    n_tasa_cupon: string;
    d_fecha_fin_cupon: string;
}

export interface FlujosDataVal {
    amort_porc: string;
    vn: string;
}

export interface RespTableClients {
    status: number;
    body: TableClients;
}

export interface TableClients {
    clientes: Record<string, string>;
    clientes_actuales: Record<string, string> | string;
}

export const fieldsToValidateIntern = [
    { name: 'n_calendario', defaultValue: 'default' },
    { name: 's_met_calc', defaultValue: 'default' },
    { name: 's_emisor', defaultValue: 'default' },
    { name: 'n_status', defaultValue: 'default' },
    { name: 's_isin', defaultValue: 'default' },
    { name: 's_crv_desc', defaultValue: 'default' },
    { name: 'n_val_nom', defaultValue: 'default' },
    { name: 's_moneda', defaultValue: 'default' },
    { name: 'd_fec_venc', defaultValue: 'default' },
    { name: 'd_fec_emi', defaultValue: 'default' },
    { name: 's_subfamilia', defaultValue: 'default' },
    { name: 's_tipo_merc', defaultValue: 'default' },
    { name: 's_tipo_instr', defaultValue: 'default' },
]

export interface RequeridosInternacional {
    [key: string]: React.MutableRefObject<HTMLInputElement | HTMLSelectElement | null>
    s_emisor: React.MutableRefObject<HTMLInputElement|HTMLSelectElement|null>
}

export interface FvInterInstrumentos extends FormValuesInter {
    n_busdayrule: string,
    n_last_reset_rate: string,
    n_moody: string,
    n_rendimiento: string,
    b_not_equal: string,
    b_couponpro: string,
    s_crv_desc: string,
    s_moneda: string,
    s_factor: string,
    n_prima: string,
    n_curve_index: string,
    n_p_cupon_vig: string,
    d_fec_venc: string,
    s_cusip: string,
    n_hr: string,
    s_serie: string,
    n_theo_model: string,
    s_familia: string,
    n_market_model: string,
    s_sector: string,
    d_fec_ini_c: string,
    n_fixed_coupon_date: string,
    s_sedol: string,
    b_precio_sucio: string,
    s_isin_v: string,
    d_fecha_sp: string,
    n_plazo: string,
    d_fecha_moody: string,
    s_emisor: string,
    s_coupgenmthd: string,
    h_flujos_hist: FlujosInter[],
    s_tasa_ref: string,
    d_fec_emi: string,
    n_frec_cupon: string,
    n_val_nom: string,
    d_fecha_amort_ant: string,
    n_num_cupon: string,
    d_fecha_fitch: string,
    s_subfamilia: string,
    n_tasa_cupon_24: string,
    n_sobretasa: string,
    n_calc_dias: string,
    b_esg: string,
    n_colateral: string,
    s_frm_coti: string,
    n_p_cupon: string,
    d_lastregcou: string,
    n_num_cupones: string,
    s_tipo: string,
    s_credit_spread_curve: string,
    s_oddlastcoupon: string,
    n_last_reset_rate_24h: string,
    n_val_nom_a: string,
    n_reset_rule: string,
    b_precio_teorico: string,
    n_tasa_cupon_md: string,
    s_met_calc: string,
    n_tipo_promedio: string,
    n_familia_esg: string,
    d_factor: string,
    b_rnv: string,
    n_pais_riesgo: string,
    s_tipo_merc: string,
    n_frec_pago: string,
    n_dias_deter_tasa: string,
    s_common: string,
    n_prec_merc: string,
    s_oddfirstcoupon: string,
    s_isin: string,
    n_fitch: string,
    n_mont_circ: string,
    b_runscfphase: string,
    n_redondeo_tasa_cupon: string,
    d_fecha_hr: string,
    s_tv: string,
    h_flujos_val: FlujosInter[],
    s_tipo_instr: string,
    n_dias_x_venc: string,
    n_sp: string,
    s_emisora: string,
    d_fec_fin_c: string,
    n_status: string,
    b_quasi_sob: string,
    n_calendario: string,
    s_bolsa_cot: string,
    s_pais: string,
    s_instrumento: string,
    n_precio_bloomberg: string,
    n_precio_markit: string,
    n_precio_reuters: string,
}

export const initialFormValuesInter: FvInterInstrumentos = {
    n_busdayrule: '',
    n_last_reset_rate: '',
    n_moody: '',
    n_rendimiento: '',
    b_not_equal: '',
    b_couponpro: '',
    s_crv_desc: '',
    s_moneda: '',
    s_factor: '',
    n_prima: '',
    n_curve_index: '',
    n_p_cupon_vig: '',
    d_fec_venc: '',
    s_cusip: '',
    n_hr: '',
    s_serie: '',
    n_theo_model: '',
    s_familia: '',
    n_market_model: '',
    s_sector: '',
    d_fec_ini_c: '',
    n_fixed_coupon_date: '',
    s_sedol: '',
    b_precio_sucio: '',
    s_isin_v: '',
    d_fecha_sp: '',
    n_plazo: '',
    d_fecha_moody: '',
    s_emisor: '',
    s_coupgenmthd: '',
    h_flujos_hist: [],
    s_tasa_ref: '',
    d_fec_emi: '',
    n_frec_cupon: '',
    n_val_nom: '',
    d_fecha_amort_ant: '',
    n_num_cupon: '',
    d_fecha_fitch: '',
    s_subfamilia: '',
    n_tasa_cupon_24: '',
    n_sobretasa: '',
    n_calc_dias: '',
    b_esg: '',
    n_colateral: '',
    s_frm_coti: '',
    n_p_cupon: '',
    d_lastregcou: '',
    n_num_cupones: '',
    s_tipo: '',
    s_credit_spread_curve: '',
    s_oddlastcoupon: '',
    n_last_reset_rate_24h: '',
    n_val_nom_a: '',
    n_reset_rule: '',
    b_precio_teorico: '',
    n_tasa_cupon_md: '',
    s_met_calc: '',
    n_tipo_promedio: '',
    n_familia_esg: '',
    d_factor: '',
    b_rnv: '',
    n_pais_riesgo: '',
    s_tipo_merc: '',
    n_frec_pago: '',
    n_dias_deter_tasa: '',
    s_common: '',
    n_prec_merc: '',
    s_oddfirstcoupon: '',
    s_isin: '',
    n_fitch: '',
    n_mont_circ: '',
    b_runscfphase: '',
    n_redondeo_tasa_cupon: '',
    d_fecha_hr: '',
    s_tv: '',
    h_flujos_val: [],
    s_tipo_instr: '',
    n_dias_x_venc: '',
    n_sp: '',
    s_emisora: '',
    d_fec_fin_c: '',
    n_status: '',
    b_quasi_sob: '',
    n_calendario: '',
    s_bolsa_cot: '',
    s_pais: '',
    s_instrumento: '',
    n_precio_bloomberg: '',
    n_precio_markit: '',
    n_precio_reuters: '',
}

export interface IsFieldModifiedFvInterIns {
    n_busdayrule: boolean,
    n_last_reset_rate: boolean,
    n_moody: boolean,
    n_rendimiento: boolean,
    b_not_equal: boolean,
    b_couponpro: boolean,
    s_crv_desc: boolean,
    s_moneda: boolean,
    s_factor: boolean,
    n_prima: boolean,
    n_curve_index: boolean,
    n_p_cupon_vig: boolean,
    d_fec_venc: boolean,
    s_cusip: boolean,
    n_hr: boolean,
    s_serie: boolean,
    n_theo_model: boolean,
    s_familia: boolean,
    n_market_model: boolean,
    s_sector: boolean,
    d_fec_ini_c: boolean,
    n_fixed_coupon_date: boolean,
    s_sedol: boolean,
    b_precio_sucio: boolean,
    s_isin_v: boolean,
    d_fecha_sp: boolean,
    n_plazo: boolean,
    d_fecha_moody: boolean,
    s_emisor: boolean,
    s_coupgenmthd: boolean,
    h_flujos_hist: boolean,
    s_tasa_ref: boolean,
    d_fec_emi: boolean,
    n_frec_cupon: boolean,
    n_val_nom: boolean,
    d_fecha_amort_ant: boolean,
    n_num_cupon: boolean,
    d_fecha_fitch: boolean,
    s_subfamilia: boolean,
    n_tasa_cupon_24: boolean,
    n_sobretasa: boolean,
    n_calc_dias: boolean,
    b_esg: boolean,
    n_colateral: boolean,
    s_frm_coti: boolean,
    n_p_cupon: boolean,
    d_lastregcou: boolean,
    n_num_cupones: boolean,
    s_tipo: boolean,
    s_credit_spread_curve: boolean,
    s_oddlastcoupon: boolean,
    n_last_reset_rate_24h: boolean,
    n_val_nom_a: boolean,
    n_reset_rule: boolean,
    b_precio_teorico: boolean,
    n_tasa_cupon_md: boolean,
    s_met_calc: boolean,
    n_tipo_promedio: boolean,
    n_familia_esg: boolean,
    d_factor: boolean,
    b_rnv: boolean,
    n_pais_riesgo: boolean,
    s_tipo_merc: boolean,
    n_frec_pago: boolean,
    n_dias_deter_tasa: boolean,
    s_common: boolean,
    n_prec_merc: boolean,
    s_oddfirstcoupon: boolean,
    s_isin: boolean,
    n_fitch: boolean,
    n_mont_circ: boolean,
    b_runscfphase: boolean,
    n_redondeo_tasa_cupon: boolean,
    d_fecha_hr: boolean,
    s_tv: boolean,
    h_flujos_val: boolean,
    s_tipo_instr: boolean,
    n_dias_x_venc: boolean,
    n_sp: boolean,
    s_emisora: boolean,
    d_fec_fin_c: boolean,
    n_status: boolean,
    b_quasi_sob: boolean,
    n_calendario: boolean,
    s_bolsa_cot: boolean,
    s_pais: boolean,
    s_instrumento: boolean,
    n_precio_bloomberg: boolean,
    n_precio_markit: boolean,
    n_precio_reuters: boolean,
}

export interface DataActPrecio {
    s_instrumento: string,
    n_precio: string,
    title_log?: string,
    msg_log?: string
}