
export interface FormValues {
    [key: string]: string | Flujos[];
}

export interface Flujos {
    property: string;
    data: FlujosData;
}

interface FlujosData {
    d_fecha_ini_cupon: string;
    n_tasa_cupon: string;
    d_fecha_fin_cupon: string;
}

export interface FvDeudaGobInstrumentos extends FormValues {
    n_busdayrule: string;
    n_last_reset_rate: string;
    n_tasa_24h: string;
    n_calif_verum_g: string;
    n_calif_moody_g: string;
    s_bolsa_emi: string;
    n_rendimiento: string;
    b_not_equal: string;
    s_com_val: string;
    d_fecha_vto: string;
    b_couponpro: string;
    s_moneda: string;
    n_calif_dbrs_g: string;
    n_tasa_mercado: string;
    n_frecuencia_cupon: string;
    n_prima: string;
    n_representante_comun: string;
    n_tipo_mercado: string;
    d_fec_moody: string;
    n_curve_index: string;
    s_evento_moody: string;
    d_fec_venc: string;
    s_cusip: string;
    s_serie: string;
    n_nomb_tasa: string;
    s_tasa:string;
    d_fec_fitch: string;
    n_agente_colocador: string;
    n_periodo_cupon_v: string;
    d_fec_dbrs: string;
    n_calif_dbrs_n: string;
    n_theo_model: string;
    n_precio_mercado_24h: string;
    d_fec_verum: string;
    n_market_model: string;
    d_fecha_subasta: string;
    n_monto_emi: string;
    b_proteccion_inflacionaria: string;
    n_fixed_coupon_date: string;
    d_fecha_vto_estimada: string;
    n_titulos_circulacion: string;
    s_sedol: string;
    n_calif_sp_g: string;
    n_tasa_48h: string;
    s_evento_sp: string;
    n_valor_nominal: string;
    n_plazo: string;
    n_tasa_referencia: string;
    s_emisor: string;
    n_precio_mercado: string;
    s_coupgenmthd: string;
    n_calif_hr_n: string;
    s_evento_dbrs: string;
    n_tipo_instrumento: string;
    s_evento_verum: string;
    n_calif_best_g: string;
    n_convencion_dias: string;
    d_fecha_fin_cupon: string;
    n_calif_sp_n: string;
    n_sobretasa: string;
    n_calif_best_n: string;
    b_esg: string;
    d_lastregcou: string;
    n_crv_descuento: string;
    n_num_cupones: string;
    n_calif_moody_n: string;
    s_credit_spread_curve: string;
    n_tasa: string;
    n_calif_fitch_n: string;
    n_calif_fitch_g: string;
    s_oddlastcoupon: string;
    s_tipo_papel: string;
    d_fecha_ini_cupon: string;
    n_last_reset_rate_24h: string;
    s_evento_hr: string;
    s_evento_fitch: string;
    n_tipo_tasa: string;
    n_emisor: string;
    n_reset_rule: string;
    n_tipo_promedio: string;
    h_flujos: Flujos[];
    n_familia_esg: string;
    n_pais_riesgo: string;
    b_rnv: string;
    d_fec_sp: string;
    s_rep_comun: string;
    s_oddfirstcoupon: string;
    s_isin: string;
    n_periodo_cupon: string;
    b_runscfphase: string;
    n_intereses_md: string;
    s_agen_col: string;
    n_calif_verum_n: string;
    n_intereses_24h: string;
    s_tv: string;
    n_forma_cotizacion: string;
    n_clasificacion_sectorial: string;
    n_familia_instrumento: string;
    n_pais: string;
    n_monto_circ: string;
    n_composicion_yield: string;
    s_evento_best: string;
    d_fec_best: string;
    d_fec_hr: string;
    s_emisora: string;
    n_num_cupon_vig: string;
    n_dia_corte_cupon: string;
    b_pago_intereses: string;
    n_status: string;
    n_moneda: string;
    s_pdf_fitch: string;
    s_pdf_sp: string;
    s_pdf_moody: string;
    s_pdf_hr: string;
    s_pdf_verum: string;
    s_pdf_dbrs: string;
    s_pdf_best: string;
    d_fec_ins: string;
    n_calif_hr_g: string;
    s_pais: string;
    d_fecha_emision: string;
    fitch_b64: string;
    sp_b64: string;
    moody_b64: string;
    hr_b64: string;
    verum_b64: string;
    dbrs_b64: string;
    best_b64: string;
}
export const initialFormValues: FvDeudaGobInstrumentos = {
    n_busdayrule: '',
    n_last_reset_rate: '',
    n_tasa_24h: '',
    n_calif_verum_g: '',
    n_calif_moody_g: '',
    s_bolsa_emi: '',
    n_rendimiento: '',
    b_not_equal: '',
    s_com_val: '',
    d_fecha_vto: '',
    b_couponpro: '',
    s_moneda: '',
    n_calif_dbrs_g: '',
    n_tasa_mercado: '',
    n_frecuencia_cupon: '',
    n_prima: '',
    n_representante_comun: '',
    n_tipo_mercado: '',
    d_fec_moody: '',
    n_curve_index: '',
    s_evento_moody: '',
    d_fec_venc: '',
    s_cusip: '',
    s_serie: '',
    s_tasa: '',
    n_nomb_tasa: '',
    d_fec_fitch: '',
    n_agente_colocador: '',
    n_periodo_cupon_v: '',
    d_fec_dbrs: '',
    n_calif_dbrs_n: '',
    n_theo_model: '',
    n_precio_mercado_24h: '',
    d_fec_verum: '',
    n_market_model: '',
    d_fecha_subasta: '',
    n_monto_emi: '',
    b_proteccion_inflacionaria: '',
    n_fixed_coupon_date: '',
    d_fecha_vto_estimada: '',
    n_titulos_circulacion: '',
    s_sedol: '',
    n_calif_sp_g: '',
    n_tasa_48h: '',
    s_evento_sp: '',
    n_valor_nominal: '',
    n_plazo: '',
    n_tasa_referencia: '',
    s_emisor: '',
    n_precio_mercado: '',
    s_coupgenmthd: '',
    n_calif_hr_n: '',
    s_evento_dbrs: '',
    n_tipo_instrumento: '',
    s_evento_verum: '',
    n_calif_best_g: '',
    n_convencion_dias: '',
    d_fecha_fin_cupon: '',
    n_calif_sp_n: '',
    n_sobretasa: '',
    n_calif_best_n: '',
    b_esg: '',
    d_lastregcou: '',
    n_crv_descuento: '',
    n_num_cupones: '',
    n_calif_moody_n: '',
    s_credit_spread_curve: '',
    n_tasa: '',
    n_calif_fitch_n: '',
    n_calif_fitch_g: '',
    s_oddlastcoupon: '',
    s_tipo_papel: '',
    d_fecha_ini_cupon: '',
    n_last_reset_rate_24h: '',
    s_evento_hr: '',
    s_evento_fitch: '',
    n_tipo_tasa: '',
    n_emisor: '',
    n_reset_rule: '',
    n_tipo_promedio: '',
    h_flujos: [],
    n_familia_esg: '',
    n_pais_riesgo: '',
    b_rnv: '',
    d_fec_sp: '',
    s_rep_comun: '',
    s_oddfirstcoupon: '',
    s_isin: '',
    n_periodo_cupon: '',
    b_runscfphase: '',
    n_intereses_md: '',
    s_agen_col: '',
    n_calif_verum_n: '',
    n_intereses_24h: '',
    s_tv: '',
    n_forma_cotizacion: '',
    n_clasificacion_sectorial: '',
    n_familia_instrumento: '',
    n_pais: '',
    n_monto_circ: '',
    n_composicion_yield: '',
    s_evento_best: '',
    d_fec_best: '',
    d_fec_hr: '',
    s_emisora: '',
    n_num_cupon_vig: '',
    n_dia_corte_cupon: '',
    b_pago_intereses: '',
    n_status: '',
    n_moneda: '',
    s_pdf_fitch: '',
    s_pdf_sp: '',
    s_pdf_moody: '',
    s_pdf_hr: '',
    s_pdf_verum: '',
    s_pdf_dbrs: '',
    s_pdf_best: '',
    d_fec_ins: '',
    n_calif_hr_g: '',
    s_pais: '',
    d_fecha_emision: '',
    fitch_b64: '',
    sp_b64: '',
    moody_b64: '',
    hr_b64: '',
    verum_b64: '',
    dbrs_b64: '',
    best_b64: ''
};