import { createAction } from "@reduxjs/toolkit";

export const updateFechaProcesoRV = createAction<string>('UPDATE_FECHA_PROCESO_RV')
export const updateSelectedVectorRV = createAction<string>('UPDATE_SELECTED_VECTOR')
export const updateIsShowLogBoxOuts = createAction<boolean>('UPDATE_SHOW_LOG_BOX_OUTS')
export const updateShowProcesoRvLog = createAction<boolean>('UPDATE_SHOW_PROCESO_RV_LOG')
export const updateShowIndicadoConsultas = createAction<boolean>('UPDATE_SHOW_INDICADO_CONSULTAS')
export const updateShowDescargaCateRv = createAction<boolean>('UPDATE_SHOW_DESCARGA_CATE_RV')
export const updateShowFormateaCateRv = createAction<boolean>('UPDATE_SHOW_FORMATEA_CATE_RV')
export const updateShowActualiza1BActBd = createAction<boolean>('UPDATE_SHOW_ACTUALIZA1B_ACT_BD')
export const updateShowNacionalActBd = createAction<boolean>('UPDATE_SHOW_NACIONAL_ACT_BD')
export const updateShowInternacionalActBd = createAction<boolean>('UPDATE_SHOW_INTERNACIONAL_ACT_BD')
export const updateCheckFormateaCateRv = createAction<boolean>('UPDATE_CHECK_FORMATEA_CATE_RV')
export const updateCheckDescargaCateRv = createAction<boolean>('UPDATE_CHECK_DESCARGA_CATE_RV')
export const updateCheckInternacionalActualizaBd = createAction<boolean>('UPDATE_CHECK_INTERNACIONAL_ACTUALIZA_BD')
export const updateCheckNacionalActualizaBd = createAction<boolean>('UPDATE_CHECK_NACIONAL_ACTUALIZA_BD')
export const updateCheckActualiza1bActualizaBd = createAction<boolean>('UPDATE_CHECK_ACTUALIZA1B_ACTUALIZA_BD')
export const updateCheckPrecalIntProcesoRv = createAction<boolean>('UPDATE_CHECK_PRECALINT_PROCESO_RV')
export const updateCheckPrecalNacProcesoRv = createAction<boolean>('UPDATE_CHECK_PRECALNAC_PROCESO_RV')
export const updateCheckGenerarSalidas = createAction<boolean>('UPDATE_CHECK_GENERAR_SALIDAS')
export const updateCheckProduccionSalidas = createAction<boolean>('UPDATE_CHECK_PRODUCCION_SALIDAS')